behavior_server:
  ros__parameters:
    costmap_topic: local_costmap/costmap_raw
    footprint_topic: local_costmap/published_footprint
    cycle_frequency: 10.0
    behavior_plugins: ["spin", "backup", "wait"]

    # Common parameters
    global_frame: odom
    robot_base_frame: robot_base_link
    transform_timeout: 0.1
    use_sim_time: False

    # Spin behavior
    spin:
      plugin: "nav2_behaviors/Spin"
      robot_base_frame: robot_base_link 
      min_rotational_vel: 0.4
      max_rotational_vel: 1.0
      rotational_acc_lim: 3.2

    # BackUp behavior
    backup:
      plugin: "nav2_behaviors/BackUp"
      robot_base_frame: robot_base_link
      speed: -0.15
      min_x_velocity_threshold: 0.01

    # Wait behavior
    wait:
      plugin: "nav2_behaviors/Wait"
      robot_base_frame: robot_base_link
      wait_duration: 10.0

